Repository AY2425S1-CS2103T-W10-2/tp, pull requests merged in 2024-10, with the labels that each got.

#37 Update target user, value proposition, and user stories in developer guide
  docs/DeveloperGuide.md
Labels: type.Task

#52 Create Command Abstractions
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/DeletePersonCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeletePersonCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddPersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeletePersonCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Task

#55 Refactor abstraction for List Command
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ListPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Task

#51 Add personId
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandIntegrationTest.java
Labels: type.Task

#61 Create model for appointments
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/AppointmentBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAppointmentBook.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/AppointmentType.java
  src/main/java/seedu/address/model/appointment/Medicine.java
  src/main/java/seedu/address/model/appointment/Sickness.java
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
  src/main/java/seedu/address/model/appointment/exceptions/AppointmentNotFoundException.java
  src/main/java/seedu/address/model/appointment/exceptions/DuplicateAppointmentException.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeletePersonCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/AppointmentBookBuilder.java
  src/test/java/seedu/address/testutil/AppointmentBuilder.java
  src/test/java/seedu/address/testutil/TypicalAppointments.java
Labels: priority.High

#58 Refractor EditCommand
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditPersonCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Task, priority.High

#67 App storage
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/AppointmentBook.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/AppointmentBookStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAppointmentBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAppointmentBook.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: type.Task, priority.High

#81 Create tests for AppointmentBookStorage
  src/test/data/JsonAppointmentBookStorageTest/invalidAndValidAppointmentBook.json
  src/test/data/JsonAppointmentBookStorageTest/invalidAppointmentBook.json
  src/test/data/JsonAppointmentBookStorageTest/notJsonFormatAppointmentBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAppointmentBookTest/duplicateAppointmentAppointmentBook.json
  src/test/data/JsonSerializableAppointmentBookTest/invalidAppointmentAppointmentBook.json
  src/test/data/JsonSerializableAppointmentBookTest/typicalAppointmentsAppointmentBook.json
  src/test/java/seedu/address/storage/JsonAdaptedAppointmentTest.java
  src/test/java/seedu/address/storage/JsonAppointmentBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAppointmentBookTest.java
Labels: priority.High

#86 feat: Delete Appointment Command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/DeleteAppointmentCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteAppointmentCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Task

#96 Update version number for release
  src/main/java/seedu/address/MainApp.java
Labels: type.Task

#98 Edit "add appt" message usage
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
Labels: type.Bug

#99 Update User Guide: FAQ
  docs/UserGuide.md
  docs/images/json/addressbook.png
  docs/images/json/appointmentBook.png
  docs/package-lock.json
  docs/package.json
Labels: type.Task

#85 Update Dev Guide - Storage
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
Labels: type.Task, priority.Medium

#88 User guide appointment commands
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#122 Update user guide format
  docs/UserGuide.md
Labels: type.Enhancement

#127 Update lists to sort based on criteria
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Name.java
Labels: type.Enhancement

#128 Update Dev Guide: UI
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
Labels: type.Task

#133 Update sequence diagrams
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
Labels: type.Enhancement

#125 UI Update
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/ui/AppointmentCard.java
  src/main/resources/view/AppointmentListCard.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: type.Task, priority.Medium

#131 Update activity diagram
  docs/DeveloperGuide.md
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/OverallFlowActivityDiagram.puml
Labels: type.Enhancement

#129 Update Sickness and Medicine to be optional
  docs/DeveloperGuide.md
  src/main/java/seedu/address/commons/util/OptionalUtil.java
  src/main/java/seedu/address/commons/util/ToStringBuilder.java
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/AppointmentDescriptor.java
  src/main/java/seedu/address/model/appointment/Medicine.java
  src/main/java/seedu/address/model/appointment/Sickness.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/test/java/seedu/address/commons/util/OptionalUtilTest.java
Labels: type.Enhancement

#150 Fix exception found in logging
  src/main/java/seedu/address/ui/AppointmentCard.java
Labels: type.Bug

#149 Update Find Person
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindPersonCommand.java
  src/main/java/seedu/address/logic/parser/FindAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FindPersonCommandParser.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindPersonCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindPersonCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Task

#162 Update DG: General Commands
  docs/DeveloperGuide.md
  docs/diagrams/ExitSequenceDiagram.puml
  docs/diagrams/HelpSequenceDiagram.puml
Labels: type.Enhancement
