Repository AY2425S1-CS2103T-W10-2/tp, pull requests merged in 2024-11, with the labels that each got.

#193 Update DG: General commands
  docs/DeveloperGuide.md
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/GeneralCommandsSequenceDiagram.puml
  docs/diagrams/HelpSequenceDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram-Logic.puml
  docs/diagrams/UndoSequenceDiagram-Model.puml
Labels: type.Enhancement

#180 Switch order in add appt error message
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
Labels: type.Bug, priority.Low

#210 Fix clear person to clear appointments
  src/main/java/seedu/address/logic/commands/ClearPersonCommand.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
Labels: type.Bug

#185 Overall code quality check
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/ClearAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ClearPersonCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
  src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindPersonCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/model/AppointmentBook.java
  src/main/java/seedu/address/model/appointment/AppointmentType.java
  src/main/java/seedu/address/model/appointment/Medicine.java
  src/main/java/seedu/address/model/appointment/Sickness.java
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/AppointmentTypeContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAppointmentBookStorage.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/FindAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListAppointmentCommandTest.java
  src/test/java/seedu/address/model/AppointmentBookTest.java
  src/test/java/seedu/address/model/appointment/UniqueAppointmentListTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.Medium, alpha-bug

#195 Update Appendix: Requirements
  docs/DeveloperGuide.md
Labels: type.Enhancement

#229 Update introduction for user guide
  docs/UserGuide.md
  docs/images/doctrack_icon.png
  docs/site.json
  docs/stylesheets/main.css
Labels: type.Task

#224 Add parsing design considerations
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#222 Adjust person duplicate
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/PersonDescriptor.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.Low, alpha-bug

#225 Adjust input validation for Phone, Sickness, Medicine
  src/main/java/seedu/address/model/appointment/Medicine.java
  src/main/java/seedu/address/model/appointment/Sickness.java
  src/main/java/seedu/address/model/person/Phone.java
  src/test/java/seedu/address/model/appointment/MedicineTest.java
  src/test/java/seedu/address/model/appointment/SicknessTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
Labels: priority.Low, alpha-bug

#206 Clean Up UI
  docs/images/Ui.png
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/resources/view/AppointmentListCard.fxml
  src/main/resources/view/LightTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StatusBarFooter.fxml
Labels: alpha-bug

#211 Fix date format
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/commons/util/DateUtil.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/main/java/seedu/address/ui/AppointmentCard.java
  src/test/java/seedu/address/commons/util/DateUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/testutil/AppointmentUtil.java
Labels: type.Bug, alpha-bug

#241 Fix help window
  docs/images/helpMessage.png
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: alpha-bug

#239 Fix colour of boxes
  docs/UserGuide.md
Labels: alpha-bug

#228 Add EP comments to code to show test case heuristics
  src/test/java/seedu/address/model/appointment/AppointmentTypeTest.java
  src/test/java/seedu/address/model/appointment/MedicineTest.java
  src/test/java/seedu/address/model/appointment/SicknessTest.java
  src/test/java/seedu/address/model/appointment/UniqueAppointmentListTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
Labels: type.Task

#232 Tips and outcome photos for user guide
  docs/UserGuide.md
  docs/images/Updated_UI.png
  docs/images/addCommandResultUG.png
  docs/images/findAlexDavidResult.png
  docs/images/findApptExample.png
Labels: priority.Medium

#249 Add command specific design considerations
  docs/DeveloperGuide.md
Labels: priority.Medium

#251 Improve code quality (model, storage, tests)
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/AppointmentDescriptor.java
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/AppointmentBookBuilder.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalAppointments.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: alpha-bug

#230 ep comments for storage test cases
  src/test/java/seedu/address/storage/JsonAdaptedAppointmentTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonAppointmentBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/JsonSerializableAppointmentBookTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.Medium, alpha-bug

#252 Review and update Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/EntityCommandSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Enhancement

#257 Fix language
  docs/DeveloperGuide.md
Labels: alpha-bug

#321 Update UG with PE-D issues
  docs/UserGuide.md
  docs/images/Updated_UI.png
  docs/images/findAlexDavidResult.png
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: type.Enhancement, type.Bug

#322 Command Message Fix
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
Labels: type.Enhancement, alpha-bug
